apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: Minio
message: Minio template
metadata:
  annotations:
    description: Deploys Minio using statefulsets

    openshift.io/display-name: minio
    openshift.io/provider-display-name: CSC
  name: minio

objects:

# Minio part
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: ${CLUSTER_NAME}
    name: ${CLUSTER_NAME}-minio
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${CLUSTER_NAME}
    template:
      metadata:
        labels:
          app: ${CLUSTER_NAME}
      spec:
        containers:
        - image: minio/minio
          name: ${CLUSTER_NAME}-minio
          ports:
          - containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
          - mountPath: /data/files
            name: ${CLUSTER_NAME}-vol
          command:
          - minio
          - server
          - /data/files
          env:
          - name: MINIO_ACCESS_KEY
            value: ${USERNAME}
          - name: MINIO_SECRET_KEY
            value: ${SALASANA}
    volumeClaimTemplates:
    - metadata:
        name: ${CLUSTER_NAME}-vol
        labels:
          app: ${CLUSTER_NAME}
      spec:
        accessModes: 
          - "ReadWriteOnce"
        resources:
          requests:
            storage: ${STORAGE_SIZE}

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${CLUSTER_NAME}
    name: ${CLUSTER_NAME}-minio
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: ${CLUSTER_NAME}

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${CLUSTER_NAME}
    name: ${CLUSTER_NAME}-minio
  spec:
    host: ${CLUSTER_NAME}-minio.rahtiapp.fi
    port:
      targetPort: 9000
    to:
      kind: Service
      name: ${CLUSTER_NAME}-minio
      weight: 100
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

parameters:
  - name: SALASANA
    description: "Secret key for minio. Hint: Use autogenerated and just copy-paste it."
    displayName: Minio secret key
    required: true
    from: '[a-zA-Z0-9]{32}'
    generate: expression

  - name: CLUSTER_NAME
    description: Name of the geoserver instance. Recommended value - your username
    displayName: Cluster name
    required: true

  - name: STORAGE_SIZE
    description: Size for persistent storage
    displayName: Persistent storage size
    required: true
    value: 1Gi

  - name: USERNAME
    required: true
    description: User key for minio
    displayName: Firewall username
    value: minio
